name: Issue works
on:
  issues:
    # open 후 assigned를 하면 동작함
    types: [assigned]
  pull_request:
    types: [closed]
jobs:
  create_issue_bransh_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
